---
- name: "Set fact for user to run docker exec under"
  ansible.builtin.set_fact:
    docker_exec_user: "{{ ansible_env.SUDO_USER | default(ansible_env.USER, true) | default(ansible_user_id, true) }}"

- name: Run the command that will export the paperless database
  community.docker.docker_container_exec:
    container: ppl-web
    command: "{{ ppl_export_cmd }}"
    docker_host: unix:///run/docker.sock
  register: export_result
  become: true
  become_user: "{{ docker_exec_user }}"
  when: ppl_export | bool

- name: "Schedule a regular export in cron"
  ansible.builtin.cron:
    name: "paperless-ngx export"
    weekday: "6"
    minute: "0"
    hour: "5"
    user: "{{ docker_exec_user }}"
    job: "/usr/bin/docker exec -t ppl-web {{ ppl_export_cmd }} >> /home/{{ docker_exec_user }}/crontab.log 2>&1"
    state: "present"
  when: ppl_export_schedule | bool
