---
- name: "Populate a variable with all currently known Storage Paths"
  ansible.builtin.uri:
    url: "{{ ppl_endpoint }}storage_paths/?page_size=100"
    method: GET
    validate_certs: false
    headers:
      Authorization: "Token {{ auth_token }}"
  register: sp_response

- name: "Create Storage Paths"
  ansible.builtin.include_tasks: sp.yml
  vars:
    sp_name: "{{ item[0] }}"
    sp_path: "{{ item[1] }}"
  with_items:
    - "{{ storagepaths }}"
